#!/bin/bash

#. ./scripts/beautifier
#
#run_action "mix local.hex --if-missing"
#run_action "mix deps.get"
#run_action "mix ecto.create"
#run_action "mix test"

mix local.hex --if-missing --force
mix local.rebar --force
mix deps.get
mix ecto.create
mix test
