# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: bobrocks777/learn-ci-elixir-postgres:0.0.7
        environment:
          MIX_ENV: test
          PGUSER: postgres
          PGPASSWORD: postgres
    working_directory: ~/learn_ci
    steps:
      - checkout
      - run:
          name: Start postgres
          command: |
            service postgresql restart
      - run:
          name: Check postgres is up and responding
          command: |
            for i in `seq 1 10`;
            do
              psql -h localhost -p 5432 -U postgres -c 'select 1;' >/dev/null && echo "Postgres responded" && exit 0
              echo -n .
              sleep 1
            done
            echo Failed to connect to local postgres on port 5432 && exit 1
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - run: ./build --verbose --force-colour
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
